version: '3'

services:
  app:
    build: .
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_ORG_ID: ${OPENAI_ORG_ID}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4-turbo}
      WORKDIR: /var/app/workdir
      GOLEM_DEBUG: ${GOLEM_DEBUG:-false}
    volumes:
      - ./workdir:/var/app/workdir
