version: '3'

services:
  app:
    build: .
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_ORG_ID: ${OPENAI_ORG_ID}
      WORKDIR: /var/app/workdir
    volumes:
      - ./workdir:/var/app/workdir
